-- OpenClaw Clean Slate Reset
-- Closes all open positions, clears history, deactivates biased learning rules,
-- resets circuit breaker, and restarts sequences.
-- Run with: psql -U openclaw -d openclaw_db -f scripts/reset-clean-slate.sql

BEGIN;

-- Force-close any open positions with $0 P&L
UPDATE positions SET
  status = 'CLOSED',
  exit_price = current_price,
  exit_time = NOW(),
  exit_reasoning = 'Clean slate reset — biased learning loop fix',
  realized_pnl = 0,
  realized_pnl_percent = 0,
  hold_hours = EXTRACT(EPOCH FROM (NOW() - entry_time)) / 3600
WHERE status = 'OPEN';

-- Clear all history tables (respecting FK order)
DELETE FROM trade_events;
DELETE FROM decisions;
DELETE FROM trades;
DELETE FROM signals;
DELETE FROM positions;
DELETE FROM indicator_snapshots;
DELETE FROM learning_history;

-- Deactivate all old learning rules (were generated by biased loop)
UPDATE learning_rules SET is_active = false WHERE is_active = true;

-- Reset circuit breaker
UPDATE circuit_breaker SET
  consecutive_losses = 0,
  is_active = false,
  activated_at = NULL,
  reactivates_at = NULL,
  last_loss_symbol = NULL,
  last_loss_pnl = NULL,
  updated_at = NOW();

-- Reset sequences
ALTER SEQUENCE positions_id_seq RESTART WITH 1;
ALTER SEQUENCE trades_id_seq RESTART WITH 1;
ALTER SEQUENCE signals_id_seq RESTART WITH 1;
ALTER SEQUENCE decisions_id_seq RESTART WITH 1;
ALTER SEQUENCE indicator_snapshots_id_seq RESTART WITH 1;
ALTER SEQUENCE learning_rules_id_seq RESTART WITH 1;
ALTER SEQUENCE learning_history_id_seq RESTART WITH 1;
ALTER SEQUENCE trade_events_id_seq RESTART WITH 1;

COMMIT;
